---
- hosts: dockerhost
  become: true
  tasks:
  - name: stop if we have old docker container
    command: docker stop sample-container
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm sample-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi sample-image
    ignore_errors: yes

  - name: building docker image
    command: docker build . -t sample-image -f /home/ubuntu/Dockerfile

  - name: creating docker image
    command: docker run -d --name sample-container -p 8082:8080 sample-image

